config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :users, only: [:show, :edit, :update]
  resources :posts do
    resources :post_comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :items do
    resources :purchases, only: [:index, :create]
    resources :item_comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :rooms, only: [:index, :new, :create, :show] do
    resources :messages, only: [:index, :create]
    collection do
      get 'search'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'ドライバー' },
    { id: 3, name: 'フェアウェイウッド' },
    { id: 4, name: 'ユーティリティー' },
    { id: 5, name: 'アイアン' },
    { id: 6, name: 'ウェッジ' },
    { id: 7, name: 'パター' },
    { id: 8, name: 'アパレル' },
    { id: 9, name: 'アクセサリー' },
    { id: 10, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items

  end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '新品・未使用' },
    { id: 3, name: '未使用に近い' },
    { id: 4, name: '目立った傷や汚れなし' },
    { id: 5, name: 'やや傷や汚れあり' },
    { id: 6, name: '傷や汚れあり' },
    { id: 7, name: '全体的に状態が悪い' }
  ]

  include ActiveHash::Associations
  has_many :items

  end

app/models/days_to_ship.rb
class DaysToShip < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '１〜２日で発送' },
    { id: 3, name: '２〜３日で発送' },
    { id: 4, name: '４〜７日で発送' }
  ]

  include ActiveHash::Associations
  has_many :items
  
end

app/models/delivery_charge.rb
class DeliveryCharge < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '着払い（購入者負担）' },
    { id: 3, name: '送料込み（出品者負担）' }
  ]

  include ActiveHash::Associations
  has_many :items
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :item_image
  has_one :purchase
  has_many :item_comments

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :condition
  belongs_to :delivery_charge
  belongs_to :prefecture
  belongs_to :days_to_ship

  validates :item_image, presence: true
  validates :item_name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 }

  validates :category_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :condition_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :delivery_charge_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :prefecture_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :days_to_ship_id, numericality: { other_than: 1, message: "can't be blank" }
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :post_image
  has_many :post_comments

  validates :text, presence: true, length: { maximum: 200 }
  validates :post_image, presence: true

  def self.search(search)
    if search != ""
      Post.where('text LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :items
  
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :shipping_address
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :users
  has_many :messages

  validates :room_name, presence: true

  def self.search(search)
    if search != ""
      Room.where('room_name LIKE(?)', "%#{search}%")
    else
      Room.all
    end
  end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :purchase
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :avatar
  has_many :posts
  has_many :items
  has_many :purchases
  has_many :rooms
  has_many :messages
  has_many :post_comments
  has_many :item_comments

  with_options presence: true do
    validates :nickname
    validates :name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :name, :avatar, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with model: @user, url: user_path, method: :patch, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      ユーザー情報入力
    </h1>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">プロフィール画像</label>
      <div class="img-upload">
        <div class="click-upload">
          <p>クリックしてファイルをアップロード</p>
            <%= f.file_field :avatar, id:"avatar-image" %>
            <% unless current_user.avatar.present? %>
              <%= image_tag "profile_default_picture.png" %>
            <% end %>
          <div id="image-list"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) GOLF太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">名前</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :name, class:"input-default", id:"name", placeholder:"例) 鈴木太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
    <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード(確認)</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">自己紹介</label>
    </div>
    <%= f.text_area :introduction, class:"input-text-default", id:"introduction", placeholder:"自己紹介をしよう" %>
  </div>
  <div class="form-group">
    <h2 class='form-bottom-text'>
      「ユーザー登録」のボタンを押すことにより、
      <span>利用規約</span>
      <br>に同意したものとみなします
    </h2>
  </div>
  <div class='user_edit-btn'>
    <%= f.submit "編集完了" ,class:"user_edit-blue-btn" %>
    <%= link_to 'もどる', user_path(params[:id]), class:"user_edit-back-btn" %>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<%= render "shared/header" %>

<%# ユーザー情報 %>
<div class='user-show'>
  <div class='user-title-bar'>
    <div class='user-title'>
      <%= @user.nickname %>のユーザーページ
    </div>
    <div class='profile-btn'>
    <%= link_to 'プロフィールの編集', edit_user_path(params[:id]), class:'profile-skyblue-btn' %>
    </div>
  </div>
  <div class='user-box'>
    <div class='profile-image'>
      <% if @user.avatar.present? %>
        <%= image_tag @user.avatar, :size =>'250x250' %>
      <% else %>
        <%= image_tag "profile_default_picture.png" %>
      <% end %>
    </div>
    <div class="user-info-box">
    <table class="info-table">
        <tbody>
          <tr>
            <th class="info-user">ニックネーム</th>
            <td class="detail-value"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="info-user">名前</th>
            <td class="detail-value"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="info-user-description">自己紹介</th>
            <td class="detail-value-description"><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%# /ユーザー情報 %>

<%# ユーザー投稿一覧 %>
<div class='user-posts'>
  <div class='user-posts-title'>
    <%= @user.nickname %>の投稿一覧
  </div>
  <div class='post-contents'>
    <div class='post-content'>
      <div class='post-lists'>
        <% @user.posts.each do |post| %>
          <%= link_to post_path(post.id) do %>
            <div class='post-list'>
              <div class='post-img-content'>
                <%= image_tag post.post_image, size:'348x350', class:"post-img" %>
              </div>
              <div class='post-user'>
                <div class='post-user-avatar'>
                  <% if post.user.avatar.present? %>
                    <%= link_to image_tag(post.user.avatar, size:'35x35', class:"post-user-img"), user_path(post.user_id) %>
                  <% else %>
                    <%= image_tag "profile_default_picture.png", size:'35x35', class:'post-user-default-img' %>
                  <% end %>
                </div>
                <div class='post-user-nickname'>
                    <%= link_to post.user.nickname, user_path(post.user_id), class:"post-nickname" %>
                </div>
              </div>
              <div class='text-box'>
                <%= post.text %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%# /ユーザー投稿一覧 %>

<%# ユーザー商品一覧 %>
<div class='user-items'>
  <div class='user-items-title'>
    <%= @user.nickname %>の商品一覧
  </div>
  <div class='item-lists'>
    <% @user.items.each do |item| %>
      <div class='item-list'>
        <div class='item-user'>
          <div class='item-user-avatar'>
            <% if item.user.avatar.present? %>
              <%= link_to image_tag(item.user.avatar, size:'35x35', class:"item-user-img"), user_path(item.user_id) %>
            <% else %>
              <%= image_tag "profile_default_picture.png", size:'35x35', class:'item-user-default-img' %>
            <% end %>
          </div>
          <div class='item-user-nickname'>
              <%= link_to item.user.nickname, user_path(item.user_id), class:"item-nickname" %>
          </div>
        </div>
        <%= link_to item_path(item.id) do %>

        <% if item.purchase.present? %>
        <div class='sold-out'>
          <span>Sold Out!!</span>
        </div>
        <% end %>

        <%= image_tag item.item_image, size:'348x350', class:"item-img" %>
        <div class='item-price'>
          <span>¥<%= item.price %></span>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<%# /ユーザー商品一覧 %>