config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :users, only: [:show, :edit, :update]
  resources :posts do
    resources :post_comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :items do
    resources :purchases, only: [:index, :create]
    resources :item_comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :rooms, only: [:index, :new, :create, :show] do
    resources :messages, only: [:index, :create]
    collection do
      get 'search'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'ドライバー' },
    { id: 3, name: 'フェアウェイウッド' },
    { id: 4, name: 'ユーティリティー' },
    { id: 5, name: 'アイアン' },
    { id: 6, name: 'ウェッジ' },
    { id: 7, name: 'パター' },
    { id: 8, name: 'アパレル' },
    { id: 9, name: 'アクセサリー' },
    { id: 10, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items

  end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '新品・未使用' },
    { id: 3, name: '未使用に近い' },
    { id: 4, name: '目立った傷や汚れなし' },
    { id: 5, name: 'やや傷や汚れあり' },
    { id: 6, name: '傷や汚れあり' },
    { id: 7, name: '全体的に状態が悪い' }
  ]

  include ActiveHash::Associations
  has_many :items

  end

app/models/days_to_ship.rb
class DaysToShip < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '１〜２日で発送' },
    { id: 3, name: '２〜３日で発送' },
    { id: 4, name: '４〜７日で発送' }
  ]

  include ActiveHash::Associations
  has_many :items
  
end

app/models/delivery_charge.rb
class DeliveryCharge < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '着払い（購入者負担）' },
    { id: 3, name: '送料込み（出品者負担）' }
  ]

  include ActiveHash::Associations
  has_many :items
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :item_image
  has_one :purchase
  has_many :item_comments

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :condition
  belongs_to :delivery_charge
  belongs_to :prefecture
  belongs_to :days_to_ship

  validates :item_image, presence: true
  validates :item_name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 }

  validates :category_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :condition_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :delivery_charge_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :prefecture_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :days_to_ship_id, numericality: { other_than: 1, message: "can't be blank" }
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :post_image
  has_many :post_comments

  validates :text, presence: true, length: { maximum: 200 }
  validates :post_image, presence: true

  def self.search(search)
    if search != ""
      Post.where('text LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :items
  
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :shipping_address
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :users
  has_many :messages

  validates :room_name, presence: true

  def self.search(search)
    if search != ""
      Room.where('room_name LIKE(?)', "%#{search}%")
    else
      Room.all
    end
  end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :purchase
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :avatar
  has_many :posts
  has_many :items
  has_many :purchases
  has_many :rooms
  has_many :messages
  has_many :post_comments
  has_many :item_comments

  with_options presence: true do
    validates :nickname
    validates :name
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    if @item.save
      redirect_to root_path
    else
      render new_item_path(@item)
    end
  end

  def show
    @item = Item.find(params[:id])
    @item_comments = @item.item_comments.includes(:user)
    @item_comment = ItemComment.new
  end

  def edit
    @item = Item.find(params[:id])
    redirect_to root_path unless current_user.id == @item.user_id && @item.purchase.blank?
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to item_path
    else
      render 'items/edit'
    end
  end

  def destroy
    item = Item.find(params[:id])
    if current_user.id == item.user_id
      item.destroy
      redirect_to root_path
    end
  end

  def search
    # params[:q]がnilではない且つ、params[:q][:name]がnilではないとき（商品名の欄が入力されているとき）
    # if params[:q] && params[:q][:name]と同じような意味合い
    if params[:q]&.dig(:item_name)
      # squishメソッドで余分なスペースを削除する
      squished_keywords = params[:q][:item_name].squish
      ## 半角スペースを区切り文字として配列を生成し、paramsに入れる
      params[:q][:item_name_cont_any] = squished_keywords.split(" ")
    end
    @q = Item.ransack(params[:q])
    @items = @q.result
  end

  private

  def item_params
    params.require(:item).permit(:item_image, :item_name, :description, :category_id, :condition_id, :delivery_charge_id,
                                 :prefecture_id, :days_to_ship_id, :price).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_index.html.erb
<div class='top-bar'>
  <div class='new'>
    <%= link_to '出品する', new_item_path, class:'new-btn' %>
  </div>
  <div class='search'>
    <%= search_form_for Item.ransack(params[:q]), url: search_items_path, html: {class: "search-form"} do |f| %>
      <%= f.text_field :item_name, placeholder: '商品名から探す', class: 'search-input' %>
      <br>
      <%= f.label :submit, class: "search-button" do %>
        <input type="submit" value="検索" class="search-btn">
        <%= f.submit :submit, id: "q_submit", style: "display: none;" %>
      <% end %>
    <% end %>
  </div>
  <div class='item-search-page'>
    <%= link_to '詳細検索ページへ', search_items_path, class:'item-search-page-btn' %>
  </div>
</div>
<div class='bar-title'>新規商品一覧</div>
<div class='item-lists'>
  <% @item.each do |item| %>
    <div class='item-list'>
      <div class='item-user'>
        <div class='item-user-avatar'>
          <% if item.user.avatar.present? %>
            <%= link_to image_tag(item.user.avatar, size:'35x35', class:"item-user-img"), user_path(item.user_id) %>
          <% else %>
            <%= image_tag "profile_default_picture.png", size:'35x35', class:'item-user-default-img' %>
          <% end %>
        </div>
        <div class='item-user-nickname'>
            <%= link_to item.user.nickname, user_path(item.user_id), class:"item-nickname" %>
        </div>
      </div>
      <%= link_to item_path(item.id) do %>

      <% if item.purchase.present? %>
      <div class='sold-out'>
        <span>Sold Out!!</span>
      </div>
      <% end %>

      <%= image_tag item.item_image, size:'348x350', class:"item-img" %>
      <div class='item-price'>
        <span>¥<%= item.price %></span>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<%= render "shared/header" %>
<div class="item-contents-row">
  <div class="item-container">
    <h3>出品する商品の情報</h3>
    <%= form_with(model: @item, url: item_path, local: true) do |f| %>
    <%# 商品の画像 %>
    <div class="field">
      <label class="weight-bold-text">商品の写真</label>
      <span class="indispensable">必須</span>
      <div class='item-image'>
        <%= f.file_field :item_image, class:'select-picture',id:"item-image" %>
        <div id="item_image-list"></div>
      </div>
    </div>
    <%# /商品の画像 %>

    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :item_name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text description", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2020年に6万円で購入したドライバーです。数回使用したため細かい傷があります。とても打ちやすいのでおすすめです。純正シャフト、フレックス:s" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text">
        <span>配送について</span>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_charge_id, DeliveryCharge.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:days_to_ship_id, DaysToShip.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span class="price-text-title">価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>

    <%= f.submit "変更する", class:'sell-btn' %>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<%= render "shared/header" %>
<div class="item-contents-row">
  <div class="item-container">
    <h3>出品する商品の情報</h3>
    <%= form_with(model: @item, local: true) do |f| %>
    <%# 商品の画像 %>
    <div class="field">
      <label class="weight-bold-text">商品の写真</label>
      <span class="indispensable">必須</span>
      <div class='item-image'>
        <%= f.file_field :item_image, class:'select-picture',id:"item-image" %>
        <div id="item_image-list"></div>
      </div>
    </div>
    <%# /商品の画像 %>

    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :item_name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text description", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2020年に6万円で購入したドライバーです。数回使用したため細かい傷があります。とても打ちやすいのでおすすめです。純正シャフト、フレックス:s" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text">
        <span>配送について</span>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_charge_id, DeliveryCharge.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:days_to_ship_id, DaysToShip.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span class="price-text-title">価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>

    <%= f.submit "出品する", class:'sell-btn' %>
    <% end %>
  </div>
</div>

app/views/items/search.html.erb
<%= render "shared/header" %>

<div class='item-search-page-show'>
  <div class='item-search-contents' id="detailed-search-result-wrapper">
    <%= search_form_for @q, url: search_items_path, class:'item-search-content', html: {id: "detailed-search-form"} do |f| %>
      <div class="search-field">
        <%= f.label :item_name, '商品名' %>
        <br>
        <%= f.text_field :item_name, placeholder: '商品名', value: params[:q]&.dig(:item_name) %>
      </div>
      <div class="search-field">
        <%= f.label :category_id_eq, 'カテゴリ' %>
        <br>
        <%= f.collection_select(:category_id_eq, Category.all, :id, :name, {include_blank: "---"}) %>
      </div>
      <div class="search-field">
        <%= f.label :price_gteq, '価格'%>
        <br>
        <%= f.number_field :price_gteq %> 円以上
        <br>
        <%= f.number_field :price_lteq %> 円以下
      </div>
      <div class="search-field">
        <%= f.label :user_nickname_cont, '出品者名' %>
        <br>
        <%= f.text_field :user_nickname_cont, placeholder: '出品者名' %>
      </div>
      <%= f.submit '絞り込む', class: "item-search-btn-show" %>
    <% end %>
  </div>
  <div class='item-lists'>
    <% @items.each do |item| %>
      <div class='item-list'>
        <div class='item-user'>
          <div class='item-user-avatar'>
            <% if item.user.avatar.present? %>
              <%= link_to image_tag(item.user.avatar, size:'35x35', class:"item-user-img"), user_path(item.user_id) %>
            <% else %>
              <%= image_tag "profile_default_picture.png", size:'35x35', class:'item-user-default-img' %>
            <% end %>
          </div>
          <div class='item-user-nickname'>
              <%= link_to item.user.nickname, user_path(item.user_id), class:"item-nickname" %>
          </div>
        </div>
        <%= link_to item_path(item.id) do %>

        <% if item.purchase.present? %>
        <div class='sold-out'>
          <span>Sold Out!!</span>
        </div>
        <% end %>

        <%= image_tag item.item_image, size:'348x350', class:"item-img" %>
        <div class='item-price'>
          <span>¥<%= item.price %></span>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.item_name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @item.item_image , class:"item-box-img" %>
      <% if @item.purchase.present? %>
      <div class="sold-out">
        <span>Sold Out!!</span>
      </div>
      <% end %>
    </div>
    <div class="item-price-box">
      <span class="item-price-show">
        ¥<%= @item.price %>
      </span>
      <span class="item-postage">
        <%= @item.delivery_charge.name %>
      </span>
    </div>

    <div class="item-explain-box">
      <span><%= @item.description %></span>
    </div>

    <% if user_signed_in? && current_user.id == @item.user_id %>
      <% unless @item.purchase.present? %>
        <%= link_to "商品の編集", edit_item_path, method: :get, class:"item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", item_path, method: :delete, class:"item-destroy" %>
      <% end %>

    <% elsif user_signed_in? && current_user.id != @item.user_id %>
      <% unless @item.purchase.present? %>
        <%= link_to "購入画面に進む", item_purchases_path(@item.id), class:"item-red-btn"%>
      <% end %>
    <% end %>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value-user">
            <div class='item-user-avatar'>
              <% if @item.user.avatar.present? %>
                <%= link_to image_tag(@item.user.avatar, size:'35x35', class:"item-user-img"), user_path(@item.user_id) %>
              <% else %>
                <%= image_tag "profile_default_picture.png", size:'35x35', class:'item-user-default-img' %>
              <% end %>
            </div>
            <div class='item-user-nickname'>
                <%= link_to @item.user.nickname, user_path(@item.user_id), class:"item-nickname" %>
            </div>
          </td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value-show"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value-show"><%= @item.condition.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value-show"><%= @item.delivery_charge.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value-show"><%= @item.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value-show"><%= @item.days_to_ship.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="item_comments">
      <h1>＜コメント一覧＞</h1>
      <div class='item_comment'>
        <% @item.item_comments.each do |item_comment| %>
          <div class="message">
            <div class="upper-message">
              <div class="message-user">
                <div class='message-user-avatar'>
                    <% if item_comment.user.avatar.present? %>
                      <%= link_to image_tag(item_comment.user.avatar, size:'25x25', class:"message-user-img"), user_path(item_comment.user_id) %>
                    <% else %>
                      <%= image_tag "profile_default_picture.png", size:'25x25', class:'message-user-default-img' %>
                    <% end %>
                  </div>
                <div class='message-user-name'>
                  <%= link_to item_comment.user.nickname, user_path(item_comment.user_id), class:"message-nickname" %>
                </div>
              </div>
              <div class="message-date">
                <%= l item_comment.created_at %>
              </div>
            </div>
            <div class="lower-message">
              <div class="message-content">
                <%= item_comment.text %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="item_comment-form">
      <%= form_with model: [@item, @item_comment], class:"item_comment-form", local: true do |f| %>
        <%= f.text_field :text , class: "item_comment-text", placeholder: 'テキストを入力'%>
        <%= f.submit "コメントをする", class: "item_comment-submit" %>
      <% end %>
    </div>
  </div>
</div>