config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :users, only: [:show, :edit, :update]
  resources :posts do
    resources :post_comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :items do
    resources :purchases, only: [:index, :create]
    resources :item_comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :rooms, only: [:index, :new, :create, :show] do
    resources :messages, only: [:index, :create]
    collection do
      get 'search'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'ドライバー' },
    { id: 3, name: 'フェアウェイウッド' },
    { id: 4, name: 'ユーティリティー' },
    { id: 5, name: 'アイアン' },
    { id: 6, name: 'ウェッジ' },
    { id: 7, name: 'パター' },
    { id: 8, name: 'アパレル' },
    { id: 9, name: 'アクセサリー' },
    { id: 10, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items

  end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '新品・未使用' },
    { id: 3, name: '未使用に近い' },
    { id: 4, name: '目立った傷や汚れなし' },
    { id: 5, name: 'やや傷や汚れあり' },
    { id: 6, name: '傷や汚れあり' },
    { id: 7, name: '全体的に状態が悪い' }
  ]

  include ActiveHash::Associations
  has_many :items

  end

app/models/days_to_ship.rb
class DaysToShip < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '１〜２日で発送' },
    { id: 3, name: '２〜３日で発送' },
    { id: 4, name: '４〜７日で発送' }
  ]

  include ActiveHash::Associations
  has_many :items
  
end

app/models/delivery_charge.rb
class DeliveryCharge < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '着払い（購入者負担）' },
    { id: 3, name: '送料込み（出品者負担）' }
  ]

  include ActiveHash::Associations
  has_many :items
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :item_image
  has_one :purchase
  has_many :item_comments

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :condition
  belongs_to :delivery_charge
  belongs_to :prefecture
  belongs_to :days_to_ship

  validates :item_image, presence: true
  validates :item_name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 }

  validates :category_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :condition_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :delivery_charge_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :prefecture_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :days_to_ship_id, numericality: { other_than: 1, message: "can't be blank" }
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :post_image
  has_many :post_comments

  validates :text, presence: true, length: { maximum: 200 }
  validates :post_image, presence: true

  def self.search(search)
    if search != ""
      Post.where('text LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :items
  
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :shipping_address
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :users
  has_many :messages

  validates :room_name, presence: true

  def self.search(search)
    if search != ""
      Room.where('room_name LIKE(?)', "%#{search}%")
    else
      Room.all
    end
  end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :purchase
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :avatar
  has_many :posts
  has_many :items
  has_many :purchases
  has_many :rooms
  has_many :messages
  has_many :post_comments
  has_many :item_comments

  with_options presence: true do
    validates :nickname
    validates :name
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  def index
    @post = Post.order('created_at DESC')
    @item = Item.order('created_at DESC')
    @room = Room.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to root_path
    else
      render new_post_path(@item)
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comments = @post.post_comments.includes(:user)
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
    redirect_to action: :index unless current_user.id == @post.user_id
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path
    else
      render 'posts/edit'
    end
  end

  def destroy
    post = Post.find(params[:id])
    if current_user.id == post.user_id
      post.destroy
      redirect_to root_path
    end
  end

  def search
    @posts = Post.search(params[:keyword])
  end

  private
  def post_params
    params.require(:post).permit(:post_image, :text).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/edit.html.erb
<%= render "shared/header" %>
<div class="contents-row">
  <div class="container">
    <h3>投稿編集</h3>
    <%= form_with(model: @post, url: post_path, local: true, method: :patch) do |form| %>
      <div class="field">
        <label class="post-picture-title">投稿する写真</label>
        <div class='post-picture'>
          <%= form.file_field :post_image, class:'select-picture',id:"post_image" %>
          <div id="picture-list"></div>
        </div>
      </div>
      <%= form.text_area :text, placeholder: "テキスト", rows: "10", class:'post-textarea' %>
      <%= form.submit "編集完了", class:'post-btn' %>
      <div class='post_edit-back'>
      <%= link_to 'もどる', post_path(params[:id]), class:"post_edit-back-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<%= render "shared/header" %>

<div class='main'>
  <div class='post-bar'>
    <div class='top-bar'>
      <div class='new'>
        <%= link_to '投稿する', new_post_path ,class:'new-btn' %>
      </div>
      <div class='search'>
        <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
          <%= form.submit "検索", class: "search-btn" %>
        <% end %>
      </div>
    </div>
    <div class='bar-title'>新規投稿一覧</div>
    <div class='post-contents'>
      <div class='post-lists'>
        <% @post.each do |post| %>
          <%= link_to post_path(post.id) do %>
            <div class='post-list'>
              <div class='post-img-content'>
                <%= image_tag post.post_image, size:'348x350', class:"post-img" %>
              </div>
              <div class='post-user'>
                <div class='post-user-avatar'>
                  <% if post.user.avatar.present? %>
                    <%= link_to image_tag(post.user.avatar, size:'35x35', class:"post-user-img"), user_path(post.user_id) %>
                  <% else %>
                    <%= image_tag "profile_default_picture.png", size:'35x35', class:'post-user-default-img' %>
                  <% end %>
                </div>
                <div class='post-user-nickname'>
                    <%= link_to post.user.nickname, user_path(post.user_id), class:"post-nickname" %>
                </div>
              </div>
              <div class='text-box'>
                <%= post.text %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class='item-bar'>
    <%= render partial: 'items/index' %>
  </div>
  <div class='room-bar'>
    <%= render partial: 'rooms/index' %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/posts/new.html.erb
<%= render "shared/header" %>
<div class="contents-row">
  <div class="container">
    <h3>新規投稿</h3>
    <%= form_with(model: @post, url: posts_path, local: true) do |form| %>
      <div class="field">
        <label class="post-picture-title">投稿する写真</label>
        <div class='post-picture'>
          <%= form.file_field :post_image, class:'select-picture',id:"post_image" %>
          <div id="picture-list"></div>
        </div>
      </div>
      <%= form.text_area :text, placeholder: "テキスト", rows: "10", class:'post-textarea' %>
      <%= form.submit "投稿する", class:'post-btn' %>
    <% end %>
  </div>
</div>

app/views/posts/search.html.erb
<%= render "shared/header" %>
<div class='post-search-page'>
  <div class='post-search-show'>
    <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
  <div class='post-contents'>
    <div class='post-content'>
      <div class='post-lists'>
        <% @posts.each do |post| %>
          <%= link_to post_path(post.id) do %>
            <div class='post-list'>
              <div class='post-img-content'>
                <%= image_tag post.post_image, size:'348x350', class:"post-img" %>
              </div>
              <div class='post-user'>
                <div class='post-user-avatar'>
                  <% if post.user.avatar.present? %>
                    <%= link_to image_tag(post.user.avatar, size:'35x35', class:"post-user-img"), user_path(post.user_id) %>
                  <% else %>
                    <%= image_tag "profile_default_picture.png", size:'35x35', class:'post-user-default-img' %>
                  <% end %>
                </div>
                <div class='post-user-nickname'>
                    <%= link_to post.user.nickname, user_path(post.user_id), class:"post-nickname" %>
                </div>
              </div>
              <div class='text-box'>
                <%= post.text %>
              </div>
            </div>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= render "shared/header" %>
<div class='post-show-main'>
  <div class='post-show-box'>
    <div class='post-show-leftbox'>
      <div class='post-show-user'>
        <div class='post-user-avatar'>
          <% if @post.user.avatar.present? %>
            <%= link_to image_tag(@post.user.avatar, size:'50x50', class:"post-user-img"), user_path(@post.user_id) %>
          <% else %>
            <%= image_tag "profile_default_picture.png", size:'50x50', class:'post-user-default-img' %>
          <% end %>
        </div>
        <div class='post-user-nickname'>
            <%= link_to @post.user.nickname, user_path(@post.user_id), class:"post-nickname" %>
        </div>
      </div>
      <div class='post-img-content'>
        <%= image_tag @post.post_image, size:'450x450', class:"post-img" %>
      </div>
      <div class='text-box'>
        <%= @post.text %>
      </div>
    </div>
    <div class='post-show-rightbox'>
      <div class='post-show-rightbox-top'>
        <% if user_signed_in? && current_user.id == @post.user_id %>
        <div class="post-more">
          <%= link_to '投稿の編集', edit_post_path(@post.id), class:'post-edit'%>
          <%= link_to '削除する', post_path(@post.id), method: :delete, class:'post-delete'%>
        </div>
        <% end %>
      </div>
      <div class='post-comment-title'>
        <h1>コメント一覧</h1>
      </div>
      <div class='post-comments', id="comments">
        <% @post.post_comments.each do |post_comment| %>
          <div class="message">
            <div class="upper-message">
              <div class="message-user">
                <div class='message-user-avatar'>
                    <% if post_comment.user.avatar.present? %>
                      <%= link_to image_tag(post_comment.user.avatar, size:'25x25', class:"message-user-img"), user_path(post_comment.user_id) %>
                    <% else %>
                      <%= image_tag "profile_default_picture.png", size:'25x25', class:'message-user-default-img' %>
                    <% end %>
                  </div>
                <div class='message-user-name'>
                  <%= link_to post_comment.user.nickname, user_path(post_comment.user_id), class:"message-nickname" %>
                </div>
              </div>
              <div class="message-date">
                <%= l post_comment.created_at %>
              </div>
            </div>
            <div class="lower-message">
              <div class="message-content">
                <%= post_comment.text %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="post_comment-form">
        <%= form_with model: [@post, @post_comment], class:"post_comment-form", local: true do |f| %>
        <div class="form-post_comment-input">
          <%= f.text_field :text , class: "form-post_comment", placeholder: 'テキストを入力'%>
        </div>
          <%= f.submit "コメントをする", class: "form-post_comment-submit" %>
        <% end %>
      </div>
    </div>
  </div>
</div>